
import { CatalogCategory, ProductItem, ProductImage } from './types';

const getCurrentISODate = () => new Date().toISOString();

// Updated to handle D/M/YYYY and DD/MM/YYYY, H:MM and HH:MM
const parseDateTimeToISO = (dateString: string, timeString: string): string => {
  const dateParts = dateString.split('/');
  const timeParts = timeString.split(':');

  const day = parseInt(dateParts[0].padStart(2, '0'));
  const month = parseInt(dateParts[1].padStart(2, '0')) - 1; // Months in JS are 0-indexed
  let year = parseInt(dateParts[2]);
  if (year < 2000) year += 2000; 

  const hour = parseInt(timeParts[0].padStart(2, '0'));
  const minute = parseInt(timeParts[1].padStart(2, '0'));
  
  try {
    const d = new Date(Date.UTC(year, month, day, hour, minute));
    if (isNaN(d.getTime())) {
        console.error(`Invalid date created for: ${dateString} ${timeString}. Using current date as fallback.`);
        return new Date().toISOString(); 
    }
    return d.toISOString();
  } catch (e) {
    console.error(`Error parsing date: ${dateString} ${timeString}`, e);
    return new Date().toISOString(); 
  }
};

const generateSpinImages = (productId: string, count: number, baseImageName?: string): ProductImage[] => {
  return Array.from({ length: count }, (_, i) => ({
    id: `spin_${productId}_${i + 1}`,
    url: baseImageName ? `/images/${baseImageName}-spin-${i + 1}.jpg` : `https://picsum.photos/seed/${productId}-spin${i + 1}/600/400`,
    isMain: false,
  }));
};

const defaultNewFields: Omit<ProductItem, 'id'|'name'|'description'|'imageUrl'|'images'|'price'|'costPrice'|'stock'|'sku'|'categoryId'|'updatedAt'|'categoryName'> = {
  subcategoryId: '',
  barcodeType: '' as const,
  eanGtin: '',
  autoSku: false,
  productCondition: 'Nuevo' as const,
  unitType: 'Pieza' as const,
  brand: '',
  hasVariations: false,
  reservedStock: 0,
  lowStockNotificationThreshold: 5,
  sizes: [],
  sizePrices: [],
  volumeMl: undefined,
  availableVolumesMl: [],
  volumePrices: [],
  spinImages: [],
};

const BRANDS_LIST = [
    "Lonkoom", "Under Armour", "Puma", "DC Shoes", "Reebok", "Original Penguin", 
    "Vans", "Asics", "Skechers", "Nike", "Adidas", "Aeropostale", "American Eagle",
    "Calvin Klein", "Nautica", "Playera Original Penguin", "Paris Hilton", "Tommy Hilfiger", 
    "Ariana Grande", "Yves Saint Laurent", "Billie Eilish", "Guess", "Lacoste", 
    "Al Rehab", "Merve", "Perry Ellis", "Bebe", "Hollister", "Salvatore Ferragamo", 
    "Elizabeth Arden", "Banana Republic", "Ralph Lauren", "Hugo Boss", "Katy Perry", 
    "Ferrioni", "Geoffrey Beene", "Oscar De La Renta",
    // New brands from image
    "Jordan", "DKNY", "Nine West", "Juicy Couture", "True Religion", "Jessica Simpson", "Steve Madden", "TH" // TH for Tommy Hilfiger
];


const extractBrandFromName = (productName: string): string => {
    const nameLower = productName.toLowerCase();
    // Check for specific multi-word brands or abbreviations first
    if (nameLower.includes("tommy hilfiger") || nameLower.includes("tommy")) return "Tommy Hilfiger";
    if (nameLower.includes("calvin klein") || nameLower.includes("ck ")) return "Calvin Klein"; // CK followed by space
    if (nameLower.includes("nine west")) return "Nine West";
    if (nameLower.includes("true religion")) return "True Religion";
    if (nameLower.includes("jessica simpson")) return "Jessica Simpson";
    if (nameLower.includes("steve madden")) return "Steve Madden";
    if (nameLower.includes("juicy couture") || nameLower.includes("juicy ")) return "Juicy Couture";


    for (const brand of BRANDS_LIST) {
        if (nameLower.includes(brand.toLowerCase())) {
            // Handle specific cases like "Playera Original Penguin"
            if (brand === "Playera Original Penguin") return "Original Penguin";
            return brand;
        }
    }
    return '';
};

const calculateCostPrice = (priceString: string): number => {
    const numericPrice = parseFloat(priceString.replace('$', '').replace(',', ''));
    if (isNaN(numericPrice)) return 0;
    return parseFloat((numericPrice * 0.6).toFixed(2));
};

const formatSellingPrice = (priceInput: string): string => {
    const numericPrice = parseFloat(priceInput.replace('$', '').replace(',', ''));
    if (isNaN(numericPrice)) return '$0.00';
    return `$${numericPrice.toFixed(2)}`;
};

const parseNewProductCostPrice = (costInput: string): number => {
    const numericCost = parseFloat(costInput.replace('$', '').replace(',', ''));
    return isNaN(numericCost) ? 0 : numericCost;
}

const extractSizeFromName = (name: string): string[] | undefined => {
    const sizeMatch = name.match(/TALLA\s+([\d.]+)\s*MX/i);
    if (sizeMatch && sizeMatch[1]) {
        return [`${sizeMatch[1]} MX`];
    }
    return undefined;
};


const newImageProductsRawData = [
    { fecha: "28/05/2025", cantidad: 1, costo: "$851", venta: "$1,350", desc: "TENIS BLANCOS CON LINEAS AZUL, ROJA BLANCA TOMMY TALLA 24.5 MX" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$760", venta: "$1,300", desc: "TENIS NEGROS G LOS ANGELES TALLA 25 MX" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$608", venta: "$850", desc: "MOCHILA BLANCA JORDAN CON DORADO" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$638", venta: "$1,250", desc: "TENIS BEIGE CON DORADO DKNY TALLA 26 MX" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$425", venta: "$950", desc: "BOLSA GRIS NINE WEST LOGO 9" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$334", venta: "$550", desc: "MONEDERO TARJETERO JUICY DOBLE CIERRE BEIGE" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$547", venta: "$950", desc: "BOLSA BLANCA TH" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$274", venta: "$650", desc: "SANDALIAS BEIGE CK TALLA 25 MX" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$274", venta: "$650", desc: "SANDALIAS BEIGE CK TALLA 26 MX" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$274", venta: "$650", desc: "SANDALIAS CK CAFE CLARO TALLA 24 MX" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$395", venta: "$750", desc: "LENTES TOMMY UNISEX NEGROS" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$395", venta: "$750", desc: "LENTES TRUE RELIGION" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$395", venta: "$750", desc: "LENTES UNISEX NEGRO" },
    { fecha: "28/05/2025", cantidad: 1, costo: "$305", venta: "$750", desc: "LENTES JESSICA SIMPSON ROSA" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$608", venta: "$1,150", desc: "BOLSA CROSSBODY TOMMY BEIGE PRINT TH STRAP CAFECITO" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$732", venta: "$1,300", desc: "BOLSA TOMMY BLANCO CON CAFECITO SE ABROCHA COMO MORRAL" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$395", venta: "$750", desc: "GORRA BLANCA TOMMY LOGO CHIQUITO" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$608", venta: "$1,150", desc: "BOLSA TOMMY CROSSBODY BEIGE CON CAFECITO, RAYAS EN MEDIO BLANA, ROJO Y AZUL" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$486", venta: "$950", desc: "BOLSA BEIGE NAUTICA" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$668", venta: "$1,200", desc: "BOLSA NEGRA TOMMY CROSSBODY" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$608", venta: "$950", desc: "BOLSA PUMA PUFF NEGRA" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$395", venta: "$750", desc: "COSMETIQUERA GUESS GRIS" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$243", venta: "$750", desc: "CARTERA BEBE GRIS LETRAS DORADAS" }, // Corrected from "CARTERA BEBE BEIGE LETRAS DORADAS" to GRIS based on the image name "GORRA BEBE AZUL" implying BEBE is brand not color, also GORRA BEIGE PUMA. Assuming "GRIS" here.
    { fecha: "29/05/2025", cantidad: 1, costo: "$608", venta: "$950", desc: "RELOJ HOMBRE STEVE MADDEN CAFE" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$335", venta: "$550", desc: "GORRA BEIGE PUMA LOGO PEQUEÑO BLANCO POR UN LADO" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$334", venta: "$550", desc: "GORRA GRIS PUMA LOGO BLANCO GRANDE" },
    { fecha: "29/05/2025", cantidad: 1, costo: "$334", venta: "$550", desc: "GORRA NARANJA LOGO NEGRO" },
    { fecha: "30/05/2025", cantidad: 1, costo: "$608", venta: "$1,200", desc: "TENIS BEIGE NAUTICA SUELA CAFE HOMBRE TALLA 28 MX" },
    { fecha: "30/05/2025", cantidad: 1, costo: "$851", venta: "$1,450", desc: "TENIS BLANCOS DAMA TOMMY, LOGO NEGRO, LINEA NEGRA EN LA PUNTA TALLA 26 MX" },
    { fecha: "30/05/2025", cantidad: 1, costo: "$395", venta: "$750", desc: "GORRA BLANCA TOMMY" },
    { fecha: "31/05/2025", cantidad: 1, costo: "$243", venta: "$650", desc: "GORRA NEGRA QUEEN CON PIEDRITAS" },
    { fecha: "31/05/2025", cantidad: 1, costo: "$243", venta: "$650", desc: "GORRA BEBE AZUL, LETRAS BRILLANTES DAMA" },
    { fecha: "31/05/2025", cantidad: 1, costo: "$1,064", venta: "$1,600", desc: "TENIS GRIS FUERTE CON GRIS CLARO HOMBRE TOMMY TALLA 28 MX" },
    { fecha: "31/05/2025", cantidad: 1, costo: "$305", venta: "$750", desc: "CARTERA NAUTICA DAMA NEGRA CON LETRAS BLANCAS" },
    { fecha: "31/05/2025", cantidad: 1, costo: "$456", venta: "$1,050", desc: "TENIS BEIGE SUELA BLANCA LENGUA CAFE MAS OSCURO TALLA 27.5 MX" },
    { fecha: "31/05/2025", cantidad: 1, costo: "$304", venta: "$750", desc: "SANDALIA NAUTICA TIPO CROC GRIS CON CAFE TALLA 27 MX" },
];

const parsedNewImageProducts: Omit<ProductItem, 'id' | 'categoryName' | 'categoryId'>[] = newImageProductsRawData.map((p, index) => {
    const sku = `NUEVO-${index + 1}`;
    const name = p.desc;
    const sizes = extractSizeFromName(name);
    const brand = extractBrandFromName(name);

    return {
        ...defaultNewFields,
        name: name,
        description: name,
        imageUrl: `/images/${sku}.jpg`,
        images: [{ id: `img_${sku}_main`, url: `/images/${sku}.jpg`, isMain: true }],
        price: formatSellingPrice(p.venta),
        costPrice: parseNewProductCostPrice(p.costo),
        stock: p.cantidad,
        sku: sku,
        updatedAt: parseDateTimeToISO(p.fecha, "00:00"),
        brand: brand,
        sizes: sizes,
        hasVariations: !!sizes,
        // BarcodeType and eanGtin remain default empty
    };
});


const existingProductDefinitions: Omit<ProductItem, 'id' | 'categoryName' | 'categoryId'>[] = [
  // Perfumes
  {
    ...defaultNewFields,
    name: 'Lonkoom 24K Pure Gold EDP 100 ml',
    description: 'Perfume Lonkoom 24K Pure Gold EDP de 100 ml.',
    imageUrl: '/images/RR0073.jpg',
    images: [{ id: 'img_RR0073_main', url: '/images/RR0073.jpg', isMain: true }],
    price: '$600.00',
    costPrice: calculateCostPrice('$600.00'),
    stock: 0,
    sku: 'RR0073',
    updatedAt: parseDateTimeToISO("9/6/2025", "18:13"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '6928075667987',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$600.00' }],
    brand: 'Lonkoom',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Lonkoom 24K Pure Pink EDP 100 ml',
    description: 'Perfume Lonkoom 24K Pure Pink EDP de 100 ml.',
    imageUrl: '/images/RR0074.jpg',
    images: [{ id: 'img_RR0074_main', url: '/images/RR0074.jpg', isMain: true }],
    price: '$600.00',
    costPrice: calculateCostPrice('$600.00'),
    stock: 0,
    sku: 'RR0074',
    updatedAt: parseDateTimeToISO("9/6/2025", "18:12"),
    barcodeType: 'UPC',
    eanGtin: '885396999073',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$600.00' }],
    brand: 'Lonkoom',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Nautica Voyage EDT 100 ml',
    description: 'Perfume Nautica Voyage EDT de 100 ml.',
    imageUrl: '/images/RR0059.jpg',
    images: [{ id: 'img_RR0059_main', url: '/images/RR0059.jpg', isMain: true }],
    price: '$350.00',
    costPrice: calculateCostPrice('$350.00'),
    stock: 0,
    sku: 'RR0059',
    updatedAt: parseDateTimeToISO("5/5/2025", "15:16"),
    barcodeType: 'UPC',
    eanGtin: '789554043915',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$350.00' }],
    brand: 'Nautica',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Paris Hilton Ruby Rush 100 ml',
    description: 'Perfume Paris Hilton Ruby Rush de 100 ml.',
    imageUrl: '/images/RR0005.jpg',
    images: [{ id: 'img_RR0005_main', url: '/images/RR0005.jpg', isMain: true }],
    price: '$650.00',
    costPrice: calculateCostPrice('$650.00'),
    stock: 2,
    sku: 'RR0005',
    updatedAt: parseDateTimeToISO("5/5/2025", "15:16"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '608940581391',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$650.00' }],
    brand: 'Paris Hilton',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Ariana Grande R.E.M. EDP 100 ml',
    description: 'Perfume Ariana Grande R.E.M. EDP de 100 ml.',
    imageUrl: '/images/RR0079.jpg',
    images: [{ id: 'img_RR0079_main', url: '/images/RR0079.jpg', isMain: true }],
    price: '$850.00',
    costPrice: calculateCostPrice('$850.00'),
    stock: 4,
    sku: 'RR0079',
    updatedAt: parseDateTimeToISO("5/5/2025", "13:16"),
    barcodeType: 'UPC',
    eanGtin: '812256025467',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$850.00' }],
    brand: 'Ariana Grande',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Calvin Klein Obsession for Men EDT 125 ml',
    description: 'Perfume Calvin Klein Obsession for Men EDT de 125 ml.',
    imageUrl: '/images/RR0069.jpg',
    images: [{ id: 'img_RR0069_main', url: '/images/RR0069.jpg', isMain: true }],
    price: '$580.00',
    costPrice: calculateCostPrice('$580.00'),
    stock: 0,
    sku: 'RR0069',
    updatedAt: parseDateTimeToISO("29/4/2025", "22:36"),
    barcodeType: 'UPC',
    eanGtin: '088300696512',
    volumeMl: 125,
    availableVolumesMl: [125],
    volumePrices: [{ volume: 125, price: '$580.00' }],
    brand: 'Calvin Klein',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Yves Saint Laurent Manifesto EDT 90 ml',
    description: 'Perfume Yves Saint Laurent Manifesto EDT de 90 ml.',
    imageUrl: '/images/RR0089.jpg',
    images: [{ id: 'img_RR0089_main', url: '/images/RR0089.jpg', isMain: true }],
    price: '$2,700.00',
    costPrice: calculateCostPrice('$2,700.00'),
    stock: 0,
    sku: 'RR0089',
    updatedAt: parseDateTimeToISO("29/4/2025", "22:35"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '3614272648425',
    volumeMl: 90,
    availableVolumesMl: [90],
    volumePrices: [{ volume: 90, price: '$2,700.00' }],
    brand: 'Yves Saint Laurent',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Billie Eilish No. 2 EDP 100 ml',
    description: 'Perfume Billie Eilish No. 2 EDP de 100 ml.',
    imageUrl: '/images/RR0088.jpg',
    images: [{ id: 'img_RR0088_main', url: '/images/RR0088.jpg', isMain: true }],
    price: '$950.00',
    costPrice: calculateCostPrice('$950.00'),
    stock: 0,
    sku: 'RR0088',
    updatedAt: parseDateTimeToISO("29/4/2025", "19:57"),
    barcodeType: 'UPC',
    eanGtin: '608940583753',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$950.00' }],
    brand: 'Billie Eilish',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Guess 1981 EDT 100 ml',
    description: 'Perfume Guess 1981 EDT de 100 ml.',
    imageUrl: '/images/RR0058.jpg',
    images: [{ id: 'img_RR0058_main', url: '/images/RR0058.jpg', isMain: true }],
    price: '$520.00',
    costPrice: calculateCostPrice('$520.00'),
    stock: 1,
    sku: 'RR0058',
    updatedAt: parseDateTimeToISO("24/4/2025", "22:50"),
    barcodeType: 'UPC',
    eanGtin: '085715321510',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$520.00' }],
    brand: 'Guess',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Yves Saint Laurent EDT 200 ml',
    description: 'Perfume Yves Saint Laurent EDT de 200 ml.',
    imageUrl: '/images/RR0071.jpg',
    images: [{ id: 'img_RR0071_main', url: '/images/RR0071.jpg', isMain: true }],
    price: '$1,100.00',
    costPrice: calculateCostPrice('$1,100.00'),
    stock: 4,
    sku: 'RR0071',
    updatedAt: parseDateTimeToISO("24/4/2025", "22:47"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '0764613213355',
    volumeMl: 200,
    availableVolumesMl: [200],
    volumePrices: [{ volume: 200, price: '$1,100.00' }],
    brand: 'Yves Saint Laurent',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Lacoste Essential EDT 125 ml',
    description: 'Perfume Lacoste Essential EDT de 125 ml.',
    imageUrl: '/images/RR0076.jpg',
    images: [{ id: 'img_RR0076_main', url: '/images/RR0076.jpg', isMain: true }],
    price: '$950.00',
    costPrice: calculateCostPrice('$950.00'),
    stock: 0,
    sku: 'RR0076',
    updatedAt: parseDateTimeToISO("24/4/2025", "22:46"),
    barcodeType: 'UPC',
    eanGtin: '737052483214',
    volumeMl: 125,
    availableVolumesMl: [125],
    volumePrices: [{ volume: 125, price: '$950.00' }],
    brand: 'Lacoste',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Al Rehab French Coffee EDP 100 ml',
    description: 'Perfume Al Rehab French Coffee EDP de 100 ml.',
    imageUrl: '/images/RR0072.jpg',
    images: [{ id: 'img_RR0072_main', url: '/images/RR0072.jpg', isMain: true }],
    price: '$950.00',
    costPrice: calculateCostPrice('$950.00'),
    stock: 2,
    sku: 'RR0072',
    updatedAt: parseDateTimeToISO("24/4/2025", "22:27"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '6291110100078',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$950.00' }],
    brand: 'Al Rehab',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Calvin Klein Escape EDT 100 ml',
    description: 'Perfume Calvin Klein Escape EDT de 100 ml.',
    imageUrl: '/images/RR0068.jpg',
    images: [{ id: 'img_RR0068_main', url: '/images/RR0068.jpg', isMain: true }],
    price: '$650.00',
    costPrice: calculateCostPrice('$650.00'),
    stock: 3,
    sku: 'RR0068',
    updatedAt: parseDateTimeToISO("24/4/2025", "19:37"),
    barcodeType: 'UPC',
    eanGtin: '689076670081',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$650.00' }],
    brand: 'Calvin Klein',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Perry Ellis Love EDP 100 ml',
    description: 'Perfume Perry Ellis Love EDP de 100 ml.',
    imageUrl: '/images/RR0078.jpg',
    images: [{ id: 'img_RR0078_main', url: '/images/RR0078.jpg', isMain: true }],
    price: '$550.00',
    costPrice: calculateCostPrice('$550.00'),
    stock: 5,
    sku: 'RR0078',
    updatedAt: parseDateTimeToISO("15/4/2025", "22:52"),
    barcodeType: 'UPC',
    eanGtin: '844061005587',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$550.00' }],
    brand: 'Perry Ellis',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Bebe by Bebe EDP 100 ml',
    description: 'Perfume Bebe by Bebe EDP de 100 ml.',
    imageUrl: '/images/RR0077.jpg',
    images: [{ id: 'img_RR0077_main', url: '/images/RR0077.jpg', isMain: true }],
    price: '$650.00',
    costPrice: calculateCostPrice('$650.00'),
    stock: 3,
    sku: 'RR0077',
    updatedAt: parseDateTimeToISO("15/4/2025", "22:34"),
    barcodeType: 'UPC',
    eanGtin: '880599482360',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$650.00' }],
    brand: 'Bebe',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Hollister Festival Vibes EDP 100 ml',
    description: 'Perfume Hollister Festival Vibes EDP de 100 ml.',
    imageUrl: '/images/RR0075.jpg',
    images: [{ id: 'img_RR0075_main', url: '/images/RR0075.jpg', isMain: true }],
    price: '$600.00',
    costPrice: calculateCostPrice('$600.00'),
    stock: 2,
    sku: 'RR0075',
    updatedAt: parseDateTimeToISO("15/4/2025", "21:51"),
    barcodeType: 'UPC',
    eanGtin: '085715268013',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$600.00' }],
    brand: 'Hollister',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Calvin Klein CK Be EDT 200 ml',
    description: 'Perfume Calvin Klein CK Be EDT de 200 ml.',
    imageUrl: '/images/RR0070.jpg',
    images: [{ id: 'img_RR0070_main', url: '/images/RR0070.jpg', isMain: true }],
    price: '$650.00',
    costPrice: calculateCostPrice('$650.00'),
    stock: 2,
    sku: 'RR0070',
    updatedAt: parseDateTimeToISO("14/4/2025", "22:55"),
    barcodeType: 'UPC',
    eanGtin: '088300104437',
    volumeMl: 200,
    availableVolumesMl: [200],
    volumePrices: [{ volume: 200, price: '$650.00' }],
    brand: 'Calvin Klein',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Guess 1981 Indigo EDT 100 ml',
    description: 'Perfume Guess 1981 Indigo EDT de 100 ml.',
    imageUrl: '/images/RR0067.jpg',
    images: [{ id: 'img_RR0067_main', url: '/images/RR0067.jpg', isMain: true }],
    price: '$520.00',
    costPrice: calculateCostPrice('$520.00'),
    stock: 1,
    sku: 'RR0067',
    updatedAt: parseDateTimeToISO("14/4/2025", "22:21"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '2724666593260',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$520.00' }],
    brand: 'Guess',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Salvatore Ferragamo Pour Homme EDT 100 ml',
    description: 'Perfume Salvatore Ferragamo Pour Homme EDT de 100 ml.',
    imageUrl: '/images/RR0066.jpg',
    images: [{ id: 'img_RR0066_main', url: '/images/RR0066.jpg', isMain: true }],
    price: '$620.00',
    costPrice: calculateCostPrice('$620.00'),
    stock: 1,
    sku: 'RR0066',
    updatedAt: parseDateTimeToISO("14/4/2025", "22:08"),
    barcodeType: 'UPC',
    eanGtin: '646875431527',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$620.00' }],
    brand: 'Salvatore Ferragamo',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Elizabeth Arden Green Tea EDP 100 ml',
    description: 'Perfume Elizabeth Arden Green Tea EDP de 100 ml.',
    imageUrl: '/images/RR0063.jpg',
    images: [{ id: 'img_RR0063_main', url: '/images/RR0063.jpg', isMain: true }],
    price: '$500.00',
    costPrice: calculateCostPrice('$500.00'),
    stock: 1,
    sku: 'RR0063',
    updatedAt: parseDateTimeToISO("14/4/2025", "21:51"),
    barcodeType: 'UPC',
    eanGtin: '085805268848',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$500.00' }],
    brand: 'Elizabeth Arden',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Merve Neon Moon EDP 100 ml',
    description: 'Perfume Merve Neon Moon EDP de 100 ml.',
    imageUrl: '/images/RR0062.jpg',
    images: [{ id: 'img_RR0062_main', url: '/images/RR0062.jpg', isMain: true }],
    price: '$850.00',
    costPrice: calculateCostPrice('$850.00'),
    stock: 1,
    sku: 'RR0062',
    updatedAt: parseDateTimeToISO("14/4/2025", "21:49"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '3760060764881',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$850.00' }],
    brand: 'Merve',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Merve Lempereur EDP 100 ml',
    description: 'Perfume Merve Lempereur EDP de 100 ml.',
    imageUrl: '/images/RR0061.jpg',
    images: [{ id: 'img_RR0061_main', url: '/images/RR0061.jpg', isMain: true }],
    price: '$850.00',
    costPrice: calculateCostPrice('$850.00'),
    stock: 1,
    sku: 'RR0061',
    updatedAt: parseDateTimeToISO("14/4/2025", "21:49"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '3760060764942',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$850.00' }],
    brand: 'Merve',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Banana Republic M EDP 125 ml',
    description: 'Perfume Banana Republic M EDP de 125 ml.',
    imageUrl: '/images/RR0064.jpg',
    images: [{ id: 'img_RR0064_main', url: '/images/RR0064.jpg', isMain: true }],
    price: '$850.00',
    costPrice: calculateCostPrice('$850.00'),
    stock: 4,
    sku: 'RR0064',
    updatedAt: parseDateTimeToISO("14/4/2025", "20:43"),
    barcodeType: 'UPC',
    eanGtin: '840797119383',
    volumeMl: 125,
    availableVolumesMl: [125],
    volumePrices: [{ volume: 125, price: '$850.00' }],
    brand: 'Banana Republic',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Guess Marciano EDT 100 ml',
    description: 'Perfume Guess Marciano EDT de 100 ml.',
    imageUrl: '/images/RR0065.jpg',
    images: [{ id: 'img_RR0065_main', url: '/images/RR0065.jpg', isMain: true }],
    price: '$520.00',
    costPrice: calculateCostPrice('$520.00'),
    stock: 2,
    sku: 'RR0065',
    updatedAt: parseDateTimeToISO("14/4/2025", "20:40"),
    barcodeType: 'UPC',
    eanGtin: '891684087926',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$520.00' }],
    brand: 'Guess',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Hollister Wave EDP 100 ml',
    description: 'Perfume Hollister Wave EDP de 100 ml.',
    imageUrl: '/images/RR0006.jpg',
    images: [{ id: 'img_RR0006_main', url: '/images/RR0006.jpg', isMain: true }],
    price: '$580.00',
    costPrice: calculateCostPrice('$580.00'),
    stock: 0,
    sku: 'RR0006',
    updatedAt: parseDateTimeToISO("12/4/2025", "9:36"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '085715261014',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$580.00' }],
    brand: 'Hollister',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Ralph Lauren Big Pony EDT 100 ml',
    description: 'Perfume Ralph Lauren Big Pony EDT de 100 ml.',
    imageUrl: '/images/RR0060.jpg',
    images: [{ id: 'img_RR0060_main', url: '/images/RR0060.jpg', isMain: true }],
    price: '$1,050.00',
    costPrice: calculateCostPrice('$1,050.00'),
    stock: 2,
    reservedStock: 1,
    sku: 'RR0060',
    updatedAt: parseDateTimeToISO("11/4/2025", "20:03"),
    barcodeType: 'UPC',
    eanGtin: '191156884894',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$1,050.00' }],
    brand: 'Ralph Lauren',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Guess EDP 75 ml',
    description: 'Perfume Guess EDP de 75 ml.',
    imageUrl: '/images/RR0057.jpg',
    images: [{ id: 'img_RR0057_main', url: '/images/RR0057.jpg', isMain: true }],
    price: '$500.00',
    costPrice: calculateCostPrice('$500.00'),
    stock: 2,
    sku: 'RR0057',
    updatedAt: parseDateTimeToISO("11/4/2025", "19:24"),
    barcodeType: 'UPC',
    eanGtin: '085715320513',
    volumeMl: 75,
    availableVolumesMl: [75],
    volumePrices: [{ volume: 75, price: '$500.00' }],
    brand: 'Guess',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Hugo Boss Deep Red EDP 90 ml',
    description: 'Perfume Hugo Boss Deep Red EDP de 90 ml.',
    imageUrl: '/images/RR0056.jpg',
    images: [{ id: 'img_RR0056_main', url: '/images/RR0056.jpg', isMain: true }],
    price: '$680.00',
    costPrice: calculateCostPrice('$680.00'),
    stock: 1,
    sku: 'RR0056',
    updatedAt: parseDateTimeToISO("11/4/2025", "18:59"),
    barcodeType: 'UPC',
    eanGtin: '737052683553',
    volumeMl: 90,
    availableVolumesMl: [90],
    volumePrices: [{ volume: 90, price: '$680.00' }],
    brand: 'Hugo Boss',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Katy Perry Spray Purr 100 ml',
    description: 'Perfume Katy Perry Spray Purr de 100 ml.',
    imageUrl: '/images/RR0007.jpg',
    images: [{ id: 'img_RR0007_main', url: '/images/RR0007.jpg', isMain: true }],
    price: '$520.00',
    costPrice: calculateCostPrice('$520.00'),
    stock: 0,
    sku: 'RR0007',
    updatedAt: parseDateTimeToISO("30/3/2025", "18:52"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '3607349312459',
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$520.00' }],
    brand: 'Katy Perry',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Set Ferrioni Sunset Vibes Malibu 100 ml',
    description: 'Set de Perfume Ferrioni Sunset Vibes Malibu de 100 ml.',
    imageUrl: '/images/RR0001.jpg',
    images: [{ id: 'img_RR0001_main', url: '/images/RR0001.jpg', isMain: true }],
    price: '$750.00',
    costPrice: calculateCostPrice('$750.00'),
    stock: 1,
    sku: 'RR0001',
    updatedAt: parseDateTimeToISO("30/3/2025", "11:39"),
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$750.00' }],
    brand: 'Ferrioni',
    hasVariations: true,
    unitType: 'Set',
  },
  {
    ...defaultNewFields,
    name: 'Grey Flannel Geoffrey Beene 120 ml',
    description: 'Perfume Grey Flannel Geoffrey Beene de 120 ml.',
    imageUrl: '/images/RR0004.jpg',
    images: [{ id: 'img_RR0004_main', url: '/images/RR0004.jpg', isMain: true }],
    price: '$450.00',
    costPrice: calculateCostPrice('$450.00'),
    stock: 0,
    sku: 'RR0004',
    updatedAt: parseDateTimeToISO("30/3/2025", "0:33"),
    volumeMl: 120,
    availableVolumesMl: [120],
    volumePrices: [{ volume: 120, price: '$450.00' }],
    brand: 'Geoffrey Beene',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Perry Ellis 360° White 100 ml',
    description: 'Perfume Perry Ellis 360° White de 100 ml.',
    imageUrl: '/images/RR0003.jpg',
    images: [{ id: 'img_RR0003_main', url: '/images/RR0003.jpg', isMain: true }],
    price: '$550.00',
    costPrice: calculateCostPrice('$550.00'),
    stock: 0,
    sku: 'RR0003',
    updatedAt: parseDateTimeToISO("30/3/2025", "0:29"),
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$550.00' }],
    brand: 'Perry Ellis',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Set Oscar De La Renta 100 ml',
    description: 'Set de Perfume Oscar De La Renta de 100 ml.',
    imageUrl: '/images/RR0002.jpg',
    images: [{ id: 'img_RR0002_main', url: '/images/RR0002.jpg', isMain: true }],
    price: '$950.00',
    costPrice: calculateCostPrice('$950.00'),
    stock: 1,
    reservedStock: 1,
    sku: 'RR0002',
    updatedAt: parseDateTimeToISO("30/3/2025", "0:20"),
    volumeMl: 100,
    availableVolumesMl: [100],
    volumePrices: [{ volume: 100, price: '$950.00' }],
    brand: 'Oscar De La Renta',
    hasVariations: true,
    unitType: 'Set',
  },
  // Calzado
  {
    ...defaultNewFields,
    name: 'Tenis Under Armour Charged Pursuit 3 24 MX',
    description: 'Tenis Under Armour Charged Pursuit 3 talla 24 MX.',
    imageUrl: '/images/RR0080.jpg',
    images: [{ id: 'img_RR0080_main', url: '/images/RR0080.jpg', isMain: true }],
    price: '$1,659.00',
    costPrice: calculateCostPrice('$1,659.00'),
    stock: 0,
    sku: 'RR0080',
    updatedAt: parseDateTimeToISO("9/6/2025", "18:11"),
    barcodeType: 'UPC',
    eanGtin: '196884141929',
    sizes: ["24 MX"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Under Armour Charged Revitalize 23.5 MX',
    description: 'Tenis Under Armour Charged Revitalize talla 23.5 MX.',
    imageUrl: '/images/RR0084.jpg',
    images: [{ id: 'img_RR0084_main', url: '/images/RR0084.jpg', isMain: true }],
    price: '$1,549.00',
    costPrice: calculateCostPrice('$1,549.00'),
    stock: 0,
    sku: 'RR0084',
    updatedAt: parseDateTimeToISO("9/6/2025", "18:11"),
    barcodeType: 'UPC',
    eanGtin: '197778149243',
    sizes: ["23.5 MX"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Under Armour Charged Surge 24 MX',
    description: 'Tenis Under Armour Charged Surge talla 24 MX.',
    imageUrl: '/images/RR0085.jpg',
    images: [{ id: 'img_RR0085_main', url: '/images/RR0085.jpg', isMain: true }],
    price: '$1,499.00',
    costPrice: calculateCostPrice('$1,499.00'),
    stock: 0,
    sku: 'RR0085',
    updatedAt: parseDateTimeToISO("9/6/2025", "18:10"),
    barcodeType: 'UPC',
    eanGtin: '196885665271',
    sizes: ["24 MX"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Suede 24.5 MX',
    description: 'Tenis Puma Suede talla 24.5 MX.',
    imageUrl: '/images/RR0082.jpg',
    images: [{ id: 'img_RR0082_main', url: '/images/RR0082.jpg', isMain: true }],
    price: '$1,299.00',
    costPrice: calculateCostPrice('$1,299.00'),
    stock: 0,
    sku: 'RR0082',
    updatedAt: parseDateTimeToISO("9/6/2025", "18:10"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4064536376639',
    sizes: ["24.5 MX"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Deportivo Futbol 27.5 MX',
    description: 'Tenis Puma Deportivo Futbol talla 27.5 MX.',
    imageUrl: '/images/RR0013.jpg',
    images: [{ id: 'img_RR0013_main', url: '/images/RR0013.jpg', isMain: true }],
    price: '$1,199.00',
    costPrice: calculateCostPrice('$1,199.00'),
    stock: 1,
    sku: 'RR0013',
    updatedAt: parseDateTimeToISO("16/5/2025", "8:50"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4067979242165',
    sizes: ["27.5 MX"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis DC Shoes Notch SN 26 MX',
    description: 'Tenis DC Shoes Notch SN talla 26 MX.',
    imageUrl: '/images/RR0049.jpg',
    images: [{ id: 'img_RR0049_main', url: '/images/RR0049.jpg', isMain: true }],
    price: '$850.00',
    costPrice: calculateCostPrice('$850.00'),
    stock: 1,
    reservedStock: 1,
    sku: 'RR0049',
    updatedAt: parseDateTimeToISO("16/5/2025", "8:45"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '0194466681887',
    sizes: ["26 MX"],
    brand: 'DC Shoes',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Reebok Court Clean 25 MX',
    description: 'Tenis Reebok Court Clean talla 25 MX.',
    imageUrl: '/images/RR0042.jpg',
    images: [{ id: 'img_RR0042_main', url: '/images/RR0042.jpg', isMain: true }],
    price: '$1,199.00',
    costPrice: calculateCostPrice('$1,199.00'),
    stock: 1,
    sku: 'RR0042',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:58"),
    barcodeType: 'UPC',
    eanGtin: '197225156947',
    sizes: ["25 MX"],
    brand: 'Reebok',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis DC Shoes Notch 26 MX',
    description: 'Tenis DC Shoes Notch talla 26 MX.',
    imageUrl: '/images/RR0050.jpg',
    images: [{ id: 'img_RR0050_main', url: '/images/RR0050.jpg', isMain: true }],
    price: '$899.00',
    costPrice: calculateCostPrice('$899.00'),
    stock: 1,
    sku: 'RR0050',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:55"),
    barcodeType: 'UPC',
    eanGtin: '191282627471',
    sizes: ["26 MX"],
    brand: 'DC Shoes',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis DC Shoes Central 27.5 MX',
    description: 'Tenis DC Shoes Central talla 27.5 MX.',
    imageUrl: '/images/RR0021.jpg',
    images: [{ id: 'img_RR0021_main', url: '/images/RR0021.jpg', isMain: true }],
    price: '$1,049.00',
    costPrice: calculateCostPrice('$1,049.00'),
    stock: 1,
    sku: 'RR0021',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:53"),
    barcodeType: 'UPC',
    eanGtin: '194466695525',
    sizes: ["27.5 MX"],
    brand: 'DC Shoes',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis DC Shoes Method 25 MX',
    description: 'Tenis DC Shoes Method talla 25 MX.',
    imageUrl: '/images/RR0030.jpg',
    images: [{ id: 'img_RR0030_main', url: '/images/RR0030.jpg', isMain: true }],
    price: '$849.00',
    costPrice: calculateCostPrice('$849.00'),
    stock: 1,
    sku: 'RR0030',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:51"),
    barcodeType: 'UPC',
    eanGtin: '194466704227',
    sizes: ["25 MX"],
    brand: 'DC Shoes',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Under Armour Charged Verssert 22.5 MX',
    description: 'Tenis Under Armour Charged Verssert talla 22.5 MX.',
    imageUrl: '/images/RR0086.jpg',
    images: [{ id: 'img_RR0086_main', url: '/images/RR0086.jpg', isMain: true }],
    price: '$1,449.00',
    costPrice: calculateCostPrice('$1,449.00'),
    stock: 1,
    sku: 'RR0086',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:49"),
    barcodeType: 'UPC',
    eanGtin: '197778120945',
    sizes: ["22.5 MX"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis DC Shoes Notch TX 27 MX',
    description: 'Tenis DC Shoes Notch TX talla 27 MX.',
    imageUrl: '/images/RR0051.jpg',
    images: [{ id: 'img_RR0051_main', url: '/images/RR0051.jpg', isMain: true }],
    price: '$849.00',
    costPrice: calculateCostPrice('$849.00'),
    stock: 1,
    sku: 'RR0051',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:47"),
    barcodeType: 'UPC',
    eanGtin: '194466708096',
    sizes: ["27 MX"],
    brand: 'DC Shoes',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis DC Shoes Flash 26.5 MX',
    description: 'Tenis DC Shoes Flash talla 26.5 MX.',
    imageUrl: '/images/RR0055.jpg',
    images: [{ id: 'img_RR0055_main', url: '/images/RR0055.jpg', isMain: true }],
    price: '$899.00',
    costPrice: calculateCostPrice('$899.00'),
    stock: 1,
    sku: 'RR0055',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:46"),
    barcodeType: 'UPC',
    eanGtin: '194466577708',
    sizes: ["26.5 MX"],
    brand: 'DC Shoes',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis DC Shoes Method TX 27 MX',
    description: 'Tenis DC Shoes Method TX talla 27 MX.',
    imageUrl: '/images/RR0052.jpg',
    images: [{ id: 'img_RR0052_main', url: '/images/RR0052.jpg', isMain: true }],
    price: '$899.00',
    costPrice: calculateCostPrice('$899.00'),
    stock: 1,
    sku: 'RR0052',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:45"),
    barcodeType: 'UPC',
    eanGtin: '194466614021',
    sizes: ["27 MX"],
    brand: 'DC Shoes',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Zapato Original Penguin Style Mau', // No size in name, assume default or general product
    description: 'Zapato Original Penguin Style Mau.',
    imageUrl: '/images/RR0024.jpg',
    images: [{ id: 'img_RR0024_main', url: '/images/RR0024.jpg', isMain: true }],
    price: '$1,249.00',
    costPrice: calculateCostPrice('$1,249.00'),
    stock: 1,
    sku: 'RR0024',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:44"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506444978484',
    brand: 'Original Penguin',
    hasVariations: false, // No size specified in name
  },
  {
    ...defaultNewFields,
    name: 'Tenis Vans Old Skool Classic Suede 23 MX',
    description: 'Tenis Vans Old Skool Classic Suede talla 23 MX.',
    imageUrl: '/images/RR0083.jpg',
    images: [{ id: 'img_RR0083_main', url: '/images/RR0083.jpg', isMain: true }],
    price: '$1,149.00',
    costPrice: calculateCostPrice('$1,149.00'),
    stock: 1,
    sku: 'RR0083',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:42"),
    barcodeType: 'UPC',
    eanGtin: '700053804678',
    sizes: ["23 MX"],
    brand: 'Vans',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Original Penguin Style Lya 24 MX',
    description: 'Tenis Original Penguin Style Lya talla 24 MX.',
    imageUrl: '/images/RR0027.jpg',
    images: [{ id: 'img_RR0027_main', url: '/images/RR0027.jpg', isMain: true }],
    price: '$1,199.00',
    costPrice: calculateCostPrice('$1,199.00'),
    stock: 1,
    sku: 'RR0027',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:41"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506444992138',
    sizes: ["24 MX"],
    brand: 'Original Penguin',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Asics Patriot 13 22.5 MX',
    description: 'Tenis Asics Patriot 13 talla 22.5 MX.',
    imageUrl: '/images/RR0087.jpg',
    images: [{ id: 'img_RR0087_main', url: '/images/RR0087.jpg', isMain: true }],
    price: '$1,649.00',
    costPrice: calculateCostPrice('$1,649.00'),
    stock: 1,
    sku: 'RR0087',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:38"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4550456733213',
    sizes: ["22.5 MX"],
    brand: 'Asics',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Reebok Energen Tech 2 23.5 MX',
    description: 'Tenis Reebok Energen Tech 2 talla 23.5 MX.',
    imageUrl: '/images/RR0090.jpg',
    images: [{ id: 'img_RR0090_main', url: '/images/RR0090.jpg', isMain: true }],
    price: '$1,399.00',
    costPrice: calculateCostPrice('$1,399.00'),
    stock: 1,
    sku: 'RR0090',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:37"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '1200161313974',
    sizes: ["23.5 MX"],
    brand: 'Reebok',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Skechers Graceful Sport 23 MX',
    description: 'Tenis Skechers Graceful Sport talla 23 MX.',
    imageUrl: '/images/RR0015.jpg',
    images: [{ id: 'img_RR0015_main', url: '/images/RR0015.jpg', isMain: true }],
    price: '$1,349.00',
    costPrice: calculateCostPrice('$1,349.00'),
    stock: 5,
    sku: 'RR0015',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:36"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '190872053324',
    sizes: ["23 MX"],
    brand: 'Skechers',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Nike Promina 23.5 MX',
    description: 'Tenis Nike Promina talla 23.5 MX.',
    imageUrl: '/images/RR0081.jpg',
    images: [{ id: 'img_RR0081_main', url: '/images/RR0081.jpg', isMain: true }],
    price: '$1,649.00',
    costPrice: calculateCostPrice('$1,649.00'),
    stock: 1,
    sku: 'RR0081',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:33"),
    barcodeType: 'UPC',
    eanGtin: '197600680616',
    sizes: ["23.5 MX"],
    brand: 'Nike',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Reebok Royal Basketball 29 MX',
    description: 'Tenis Reebok Royal Basketball talla 29 MX.',
    imageUrl: '/images/RR0044.jpg',
    images: [{ id: 'img_RR0044_main', url: '/images/RR0044.jpg', isMain: true }],
    price: '$1,499.00',
    costPrice: calculateCostPrice('$1,499.00'),
    stock: 2,
    sku: 'RR0044',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:32"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4059814253740',
    sizes: ["29 MX"],
    brand: 'Reebok',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Aeropostale Violet 23 MX',
    description: 'Tenis Aeropostale Violet talla 23 MX.',
    imageUrl: '/images/RR0092.jpg',
    images: [{ id: 'img_RR0092_main', url: '/images/RR0092.jpg', isMain: true }],
    price: '$849.00',
    costPrice: calculateCostPrice('$849.00'),
    stock: 1,
    sku: 'RR0092',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:31"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506351687400',
    sizes: ["23 MX"],
    brand: 'Aeropostale',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Skechers Summits Diamond 22.5 MX',
    description: 'Tenis Skechers Summits Diamond talla 22.5 MX.',
    imageUrl: '/images/RR0031.jpg',
    images: [{ id: 'img_RR0031_main', url: '/images/RR0031.jpg', isMain: true }],
    price: '$1,399.00',
    costPrice: calculateCostPrice('$1,399.00'),
    stock: 1,
    sku: 'RR0031',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:30"),
    barcodeType: 'UPC',
    eanGtin: '193642279955',
    sizes: ["22.5 MX"],
    brand: 'Skechers',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Adidas Questar 26 MX',
    description: 'Tenis Adidas Questar talla 26 MX.',
    imageUrl: '/images/RR0040.jpg',
    images: [{ id: 'img_RR0040_main', url: '/images/RR0040.jpg', isMain: true }],
    price: '$1,549.00',
    costPrice: calculateCostPrice('$1,549.00'),
    stock: 1,
    sku: 'RR0040',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:16"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4066765268297',
    sizes: ["26 MX"],
    brand: 'Adidas',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Original Penguin Style Rachel 25 MX',
    description: 'Tenis Original Penguin Style Rachel talla 25 MX.',
    imageUrl: '/images/RR0026.jpg',
    images: [{ id: 'img_RR0026_main', url: '/images/RR0026.jpg', isMain: true }],
    price: '$1,049.00',
    costPrice: calculateCostPrice('$1,049.00'),
    stock: 2,
    sku: 'RR0026',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:15"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506444992701',
    sizes: ["25 MX"],
    brand: 'Original Penguin',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Under Armour Casual Essential Sportstyle 27 MX',
    description: 'Tenis Under Armour Casual Essential Sportstyle talla 27 MX.',
    imageUrl: '/images/RR0047.jpg',
    images: [{ id: 'img_RR0047_main', url: '/images/RR0047.jpg', isMain: true }],
    price: '$1,499.00',
    costPrice: calculateCostPrice('$1,499.00'),
    stock: 1,
    sku: 'RR0047',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:14"),
    barcodeType: 'UPC',
    eanGtin: '195252753566',
    sizes: ["27 MX"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Under Armour Charged Speed 25.5 MX',
    description: 'Tenis Under Armour Charged Speed talla 25.5 MX.',
    imageUrl: '/images/RR0045.jpg',
    images: [{ id: 'img_RR0045_main', url: '/images/RR0045.jpg', isMain: true }],
    price: '$1,499.00',
    costPrice: calculateCostPrice('$1,499.00'),
    stock: 1,
    sku: 'RR0045',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:14"),
    barcodeType: 'UPC',
    eanGtin: '197777775016',
    sizes: ["25.5 MX"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Pacer Easy Street 20 MX',
    description: 'Tenis Puma Pacer Easy Street talla 20 MX.',
    imageUrl: '/images/RR0038.jpg',
    images: [{ id: 'img_RR0038_main', url: '/images/RR0038.jpg', isMain: true }],
    price: '$1,199.00',
    costPrice: calculateCostPrice('$1,199.00'),
    stock: 1,
    sku: 'RR0038',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:14"),
    barcodeType: 'UPC',
    eanGtin: '195099907948',
    sizes: ["20 MX"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Original Penguin Style Brenda 23 MX',
    description: 'Tenis Original Penguin Style Brenda talla 23 MX.',
    imageUrl: '/images/RR0018.jpg',
    images: [{ id: 'img_RR0018_main', url: '/images/RR0018.jpg', isMain: true }],
    price: '$1,199.00',
    costPrice: calculateCostPrice('$1,199.00'),
    stock: 2,
    reservedStock: 1,
    sku: 'RR0018',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:12"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506444992985',
    sizes: ["23 MX"],
    brand: 'Original Penguin',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Vans Old Skool 26 MX',
    description: 'Tenis Vans Old Skool talla 26 MX.',
    imageUrl: '/images/RR0029.jpg',
    images: [{ id: 'img_RR0029_main', url: '/images/RR0029.jpg', isMain: true }],
    price: '$1,349.00',
    costPrice: calculateCostPrice('$1,349.00'),
    stock: 1,
    sku: 'RR0029',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:11"),
    barcodeType: 'UPC',
    eanGtin: '197065777166',
    sizes: ["26 MX"],
    brand: 'Vans',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Vans Sk8-hi Reissue 19.5 MX',
    description: 'Tenis Vans Sk8-hi Reissue talla 19.5 MX.',
    imageUrl: '/images/RR0020.jpg',
    images: [{ id: 'img_RR0020_main', url: '/images/RR0020.jpg', isMain: true }],
    price: '$1,099.00',
    costPrice: calculateCostPrice('$1,099.00'),
    stock: 1,
    sku: 'RR0020',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:10"),
    barcodeType: 'UPC',
    eanGtin: '196571197192',
    sizes: ["19.5 MX"],
    brand: 'Vans',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Reebok Active Lite 26 MX',
    description: 'Tenis Reebok Active Lite talla 26 MX.',
    imageUrl: '/images/RR0043.jpg',
    images: [{ id: 'img_RR0043_main', url: '/images/RR0043.jpg', isMain: true }],
    price: '$1,299.00',
    costPrice: calculateCostPrice('$1,299.00'),
    stock: 1,
    sku: 'RR0043',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:08"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '1200143536124',
    sizes: ["26 MX"],
    brand: 'Reebok',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Flyer Runner 25 MX',
    description: 'Tenis Puma Flyer Runner talla 25 MX.',
    imageUrl: '/images/RR0035.jpg',
    images: [{ id: 'img_RR0035_main', url: '/images/RR0035.jpg', isMain: true }],
    price: '$1,349.00',
    costPrice: calculateCostPrice('$1,349.00'),
    stock: 1,
    sku: 'RR0035',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:08"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4062451589646',
    sizes: ["25 MX"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Reebok Ztaur Run 28 MX',
    description: 'Tenis Reebok Ztaur Run talla 28 MX.',
    imageUrl: '/images/RR0011.jpg',
    images: [{ id: 'img_RR0011_main', url: '/images/RR0011.jpg', isMain: true }],
    price: '$1,449.00',
    costPrice: calculateCostPrice('$1,449.00'),
    stock: 1,
    sku: 'RR0011',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:07"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '195743653863',
    sizes: ["28 MX"],
    brand: 'Reebok',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Adidas Puremotion 2.0 27 MX',
    description: 'Tenis Adidas Puremotion 2.0 talla 27 MX.',
    imageUrl: '/images/RR0039.jpg',
    images: [{ id: 'img_RR0039_main', url: '/images/RR0039.jpg', isMain: true }],
    price: '$1,649.00',
    costPrice: calculateCostPrice('$1,649.00'),
    stock: 1,
    sku: 'RR0039',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:07"),
    barcodeType: 'UPC',
    eanGtin: '195746482668',
    sizes: ["27 MX"],
    brand: 'Adidas',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Original Penguin Style Helen 25 MX',
    description: 'Tenis Original Penguin Style Helen talla 25 MX.',
    imageUrl: '/images/RR0023.jpg',
    images: [{ id: 'img_RR0023_main', url: '/images/RR0023.jpg', isMain: true }],
    price: '$1,199.00',
    costPrice: calculateCostPrice('$1,199.00'),
    stock: 1,
    sku: 'RR0023',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:06"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506444954945',
    sizes: ["25 MX"],
    brand: 'Original Penguin',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Reebok Jogger Lite 28 MX',
    description: 'Tenis Reebok Jogger Lite talla 28 MX.',
    imageUrl: '/images/RR0019.jpg',
    images: [{ id: 'img_RR0019_main', url: '/images/RR0019.jpg', isMain: true }],
    price: '$1,299.00',
    costPrice: calculateCostPrice('$1,299.00'),
    stock: 1,
    sku: 'RR0019',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:05"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '1200143198261',
    sizes: ["28 MX"],
    brand: 'Reebok',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Cell Thrill 25.5 MX',
    description: 'Tenis Puma Cell Thrill talla 25.5 MX.',
    imageUrl: '/images/RR0016.jpg',
    images: [{ id: 'img_RR0016_main', url: '/images/RR0016.jpg', isMain: true }],
    price: '$1,499.00',
    costPrice: calculateCostPrice('$1,499.00'),
    stock: 1,
    sku: 'RR0016',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:05"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4067979232821',
    sizes: ["25.5 MX"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma UP 27.5 MX',
    description: 'Tenis Puma UP talla 27.5 MX.',
    imageUrl: '/images/RR0009.jpg',
    images: [{ id: 'img_RR0009_main', url: '/images/RR0009.jpg', isMain: true }],
    price: '$1,049.00',
    costPrice: calculateCostPrice('$1,049.00'),
    stock: 1,
    sku: 'RR0009',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:04"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4065452797744',
    sizes: ["27.5 MX"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Original Penguin Style Elsie 24 MX',
    description: 'Tenis Original Penguin Style Elsie talla 24 MX.',
    imageUrl: '/images/RR0028.jpg',
    images: [{ id: 'img_RR0028_main', url: '/images/RR0028.jpg', isMain: true }],
    price: '$959.00',
    costPrice: calculateCostPrice('$959.00'),
    stock: 1,
    sku: 'RR0028',
    updatedAt: parseDateTimeToISO("13/5/2025", "15:03"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506444998796',
    sizes: ["24 MX"],
    brand: 'Original Penguin',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Original Penguin Style Janny 25 MX',
    description: 'Tenis Original Penguin Style Janny talla 25 MX.',
    imageUrl: '/images/RR0025.jpg',
    images: [{ id: 'img_RR0025_main', url: '/images/RR0025.jpg', isMain: true }],
    price: '$999.00',
    costPrice: calculateCostPrice('$999.00'),
    stock: 1,
    sku: 'RR0025',
    updatedAt: parseDateTimeToISO("13/5/2025", "14:58"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506444982641',
    sizes: ["25 MX"],
    brand: 'Original Penguin',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Prowl Slip On Knit 25 MX',
    description: 'Tenis Puma Prowl Slip On Knit talla 25 MX.',
    imageUrl: '/images/RR0037.jpg',
    images: [{ id: 'img_RR0037_main', url: '/images/RR0037.jpg', isMain: true }],
    price: '$1,199.00',
    costPrice: calculateCostPrice('$1,199.00'),
    stock: 1,
    sku: 'RR0037',
    updatedAt: parseDateTimeToISO("13/5/2025", "14:57"),
    barcodeType: 'UPC',
    eanGtin: '195099136423',
    sizes: ["25 MX"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Retaliate 3 23.5 MX',
    description: 'Tenis Puma Retaliate 3 talla 23.5 MX.',
    imageUrl: '/images/RR0091.jpg',
    images: [{ id: 'img_RR0091_main', url: '/images/RR0091.jpg', isMain: true }],
    price: '$1,599.00',
    costPrice: calculateCostPrice('$1,599.00'),
    stock: 1,
    sku: 'RR0091',
    updatedAt: parseDateTimeToISO("13/5/2025", "14:55"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4067979627337',
    sizes: ["23.5 MX"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Adidas VL Court 3.0 26 XM', // Note: XM instead of MX, assume typo for MX
    description: 'Tenis Adidas VL Court 3.0 talla 26 MX.',
    imageUrl: '/images/RR0113.jpg',
    images: [{ id: 'img_RR0113_main', url: '/images/RR0113.jpg', isMain: true }],
    price: '$1,200.00',
    costPrice: calculateCostPrice('$1,200.00'),
    stock: 0,
    sku: 'RR0113',
    updatedAt: parseDateTimeToISO("12/5/2025", "20:00"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4067889068343',
    sizes: ["26 MX"],
    brand: 'Adidas',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Skyrocket', // No size in name
    description: 'Tenis Puma Skyrocket.',
    imageUrl: '/images/RR0036.jpg',
    images: [{ id: 'img_RR0036_main', url: '/images/RR0036.jpg', isMain: true }],
    price: '$1,350.00',
    costPrice: calculateCostPrice('$1,350.00'),
    stock: 0,
    sku: 'RR0036',
    updatedAt: parseDateTimeToISO("5/5/2025", "15:13"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4099686105327',
    brand: 'Puma',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Tommy Hilfiger', // No size in name
    description: 'Tenis Tommy Hilfiger.',
    imageUrl: '/images/RR0012.jpg',
    images: [{ id: 'img_RR0012_main', url: '/images/RR0012.jpg', isMain: true }],
    price: '$1,700.00',
    costPrice: calculateCostPrice('$1,700.00'),
    stock: 0,
    sku: 'RR0012',
    updatedAt: parseDateTimeToISO("5/5/2025", "15:11"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '8720646017423',
    brand: 'Tommy Hilfiger',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Redeem Profoam', // No size in name
    description: 'Tenis Puma Redeem Profoam.',
    imageUrl: '/images/RR0033.jpg',
    images: [{ id: 'img_RR0033_main', url: '/images/RR0033.jpg', isMain: true }],
    price: '$1,250.00',
    costPrice: calculateCostPrice('$1,250.00'),
    stock: 0,
    sku: 'RR0033',
    updatedAt: parseDateTimeToISO("29/4/2025", "22:40"),
    barcodeType: 'UPC',
    eanGtin: '195730462737',
    brand: 'Puma',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Original Penguin Style Lise', // No size in name
    description: 'Tenis Original Penguin Style Lise.',
    imageUrl: '/images/RR0022.jpg',
    images: [{ id: 'img_RR0022_main', url: '/images/RR0022.jpg', isMain: true }],
    price: '$750.00',
    costPrice: calculateCostPrice('$750.00'),
    stock: 0,
    sku: 'RR0022',
    updatedAt: parseDateTimeToISO("29/4/2025", "21:15"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506444982689',
    brand: 'Original Penguin',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Penguin Style Penelope', // No size in name
    description: 'Tenis Original Penguin Style Penelope.',
    imageUrl: '/images/RR0032.jpg',
    images: [{ id: 'img_RR0032_main', url: '/images/RR0032.jpg', isMain: true }],
    price: '$950.00',
    costPrice: calculateCostPrice('$950.00'),
    stock: 0,
    sku: 'RR0032',
    updatedAt: parseDateTimeToISO("24/4/2025", "22:24"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7506444988117',
    brand: 'Original Penguin',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Softride Orla', // No size in name
    description: 'Tenis Puma Softride Orla.',
    imageUrl: '/images/RR0034.jpg',
    images: [{ id: 'img_RR0034_main', url: '/images/RR0034.jpg', isMain: true }],
    price: '$1,300.00',
    costPrice: calculateCostPrice('$1,300.00'),
    stock: 0,
    sku: 'RR0034',
    updatedAt: parseDateTimeToISO("24/4/2025", "22:21"),
    barcodeType: 'UPC',
    eanGtin: '196857673723',
    brand: 'Puma',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis DC Shoes Method SN', // No size in name
    description: 'Tenis DC Shoes Method SN.',
    imageUrl: '/images/RR0054.jpg',
    images: [{ id: 'img_RR0054_main', url: '/images/RR0054.jpg', isMain: true }],
    price: '$800.00',
    costPrice: calculateCostPrice('$800.00'),
    stock: 0,
    sku: 'RR0054',
    updatedAt: parseDateTimeToISO("2/4/2025", "21:48"),
    barcodeType: 'UPC',
    eanGtin: '194466704784',
    brand: 'DC Shoes',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis DC Shoes Method', // No size in name
    description: 'Tenis DC Shoes Method.',
    imageUrl: '/images/RR0053.jpg',
    images: [{ id: 'img_RR0053_main', url: '/images/RR0053.jpg', isMain: true }],
    price: '$1,000.00',
    costPrice: calculateCostPrice('$1,000.00'),
    stock: 0,
    sku: 'RR0053',
    updatedAt: parseDateTimeToISO("2/4/2025", "21:40"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '0194466707662',
    brand: 'DC Shoes',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Skechers Summits Gray', // No size in name
    description: 'Tenis Skechers Summits Gray.',
    imageUrl: '/images/RR0017.jpg',
    images: [{ id: 'img_RR0017_main', url: '/images/RR0017.jpg', isMain: true }],
    price: '$1,300.00',
    costPrice: calculateCostPrice('$1,300.00'),
    stock: 0,
    sku: 'RR0017',
    updatedAt: parseDateTimeToISO("2/4/2025", "20:32"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '196989055893',
    brand: 'Skechers',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Under Armour Charged Verssert', // No size in name
    description: 'Tenis Under Armour Charged Verssert.',
    imageUrl: '/images/RR0048.jpg',
    images: [{ id: 'img_RR0048_main', url: '/images/RR0048.jpg', isMain: true }],
    price: '$1,550.00',
    costPrice: calculateCostPrice('$1,550.00'),
    stock: 0,
    sku: 'RR0048',
    updatedAt: parseDateTimeToISO("1/4/2025", "23:21"),
    barcodeType: 'UPC',
    eanGtin: '196885847479',
    brand: 'Under Armour',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Under Armour Phade', // No size in name
    description: 'Tenis Under Armour Phade.',
    imageUrl: '/images/RR0046.jpg',
    images: [{ id: 'img_RR0046_main', url: '/images/RR0046.jpg', isMain: true }],
    price: '$1,500.00',
    costPrice: calculateCostPrice('$1,500.00'),
    stock: 0,
    sku: 'RR0046',
    updatedAt: parseDateTimeToISO("1/4/2025", "22:13"),
    barcodeType: 'UPC',
    eanGtin: '195252308988',
    brand: 'Under Armour',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Reebok Court Advance', // No size in name
    description: 'Tenis Reebok Court Advance.',
    imageUrl: '/images/RR0041.jpg',
    images: [{ id: 'img_RR0041_main', url: '/images/RR0041.jpg', isMain: true }],
    price: '$1,550.00',
    costPrice: calculateCostPrice('$1,550.00'),
    stock: 0,
    sku: 'RR0041',
    updatedAt: parseDateTimeToISO("1/4/2025", "20:43"),
    barcodeType: 'UPC',
    eanGtin: '197225155209',
    brand: 'Reebok',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Reebok BB 1000', // No size in name
    description: 'Tenis Reebok BB 1000.',
    imageUrl: '/images/RR0010.jpg',
    images: [{ id: 'img_RR0010_main', url: '/images/RR0010.jpg', isMain: true }],
    price: '$1,200.00',
    costPrice: calculateCostPrice('$1,200.00'),
    stock: 0,
    sku: 'RR0010',
    updatedAt: parseDateTimeToISO("31/3/2025", "23:36"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '1200161333729',
    brand: 'Reebok',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Reebok Royal', // No size in name
    description: 'Tenis Reebok Royal.',
    imageUrl: '/images/RR0014.jpg',
    images: [{ id: 'img_RR0014_main', url: '/images/RR0014.jpg', isMain: true }],
    price: '$1,250.00',
    costPrice: calculateCostPrice('$1,250.00'),
    stock: 0,
    sku: 'RR0014',
    updatedAt: parseDateTimeToISO("31/3/2025", "23:34"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4065426684001',
    brand: 'Reebok',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Tenis Puma Reflect Lite', // No size in name
    description: 'Tenis Puma Reflect Lite.',
    imageUrl: '/images/RR0008.jpg',
    images: [{ id: 'img_RR0008_main', url: '/images/RR0008.jpg', isMain: true }],
    price: '$1,250.00',
    costPrice: calculateCostPrice('$1,250.00'),
    stock: 0,
    sku: 'RR0008',
    updatedAt: parseDateTimeToISO("31/3/2025", "19:49"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4099683226940',
    brand: 'Puma',
    hasVariations: false,
  },
  // Ropa
  {
    ...defaultNewFields,
    name: 'Playera Under Armour Talla M',
    description: 'Playera Under Armour Talla M.',
    imageUrl: '/images/RR0112.jpg',
    images: [{ id: 'img_RR0112_main', url: '/images/RR0112.jpg', isMain: true }],
    price: '$499.00',
    costPrice: calculateCostPrice('$499.00'),
    stock: 1,
    sku: 'RR0112',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:55"),
    barcodeType: 'UPC',
    eanGtin: '196885436246',
    sizes: ["M"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Adidas Talla M',
    description: 'Playera Adidas Talla M.',
    imageUrl: '/images/RR0111.jpg',
    images: [{ id: 'img_RR0111_main', url: '/images/RR0111.jpg', isMain: true }],
    price: '$299.00',
    costPrice: calculateCostPrice('$299.00'),
    stock: 1,
    sku: 'RR0111',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:49"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4064044864208',
    sizes: ["M"],
    brand: 'Adidas',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Sudadera Under Armour Talla G',
    description: 'Sudadera Under Armour Talla G.',
    imageUrl: '/images/RR0094.jpg',
    images: [{ id: 'img_RR0094_main', url: '/images/RR0094.jpg', isMain: true }],
    price: '$799.00',
    costPrice: calculateCostPrice('$799.00'),
    stock: 1,
    sku: 'RR0094',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:32"),
    barcodeType: 'UPC',
    eanGtin: '196885549717',
    sizes: ["G"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Conjunto Deportivo Under Armour Talla M',
    description: 'Conjunto Deportivo Under Armour Talla M.',
    imageUrl: '/images/RR0096.jpg',
    images: [{ id: 'img_RR0096_main', url: '/images/RR0096.jpg', isMain: true }],
    price: '$1,499.00',
    costPrice: calculateCostPrice('$1,499.00'),
    stock: 1,
    sku: 'RR0096',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:31"),
    barcodeType: 'UPC',
    eanGtin: '197779716888',
    sizes: ["M"],
    brand: 'Under Armour',
    unitType: 'Set',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Under Armour Talla G',
    description: 'Playera Under Armour Talla G.',
    imageUrl: '/images/RR0097.jpg',
    images: [{ id: 'img_RR0097_main', url: '/images/RR0097.jpg', isMain: true }],
    price: '$519.00',
    costPrice: calculateCostPrice('$519.00'),
    stock: 1,
    sku: 'RR0097',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:30"),
    barcodeType: 'UPC',
    eanGtin: '197779697200',
    sizes: ["G"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Puma Estampada Talla ECH',
    description: 'Playera Puma Estampada Talla ECH (Extra Chica).',
    imageUrl: '/images/RR0099.jpg',
    images: [{ id: 'img_RR0099_main', url: '/images/RR0099.jpg', isMain: true }],
    price: '$449.00',
    costPrice: calculateCostPrice('$449.00'),
    stock: 1,
    sku: 'RR0099',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:30"),
    barcodeType: 'UPC',
    eanGtin: '197674118374',
    sizes: ["XCH"], // Standardized ECH to XCH
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Puma Hyper Tank Talla G',
    description: 'Playera Puma Hyper Tank Talla G.',
    imageUrl: '/images/RR0100.jpg',
    images: [{ id: 'img_RR0100_main', url: '/images/RR0100.jpg', isMain: true }],
    price: '$499.00',
    costPrice: calculateCostPrice('$499.00'),
    stock: 1,
    sku: 'RR0100',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:29"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4067983418747',
    sizes: ["G"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Puma Ultra Talla G',
    description: 'Playera Puma Ultra Talla G.',
    imageUrl: '/images/RR0101.jpg',
    images: [{ id: 'img_RR0101_main', url: '/images/RR0101.jpg', isMain: true }],
    price: '$579.00',
    costPrice: calculateCostPrice('$579.00'),
    stock: 1,
    sku: 'RR0101',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:29"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '4067981119189',
    sizes: ["G"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Calvin Klein Talla M',
    description: 'Playera Calvin Klein Talla M.',
    imageUrl: '/images/RR0102.jpg',
    images: [{ id: 'img_RR0102_main', url: '/images/RR0102.jpg', isMain: true }],
    price: '$579.00',
    costPrice: calculateCostPrice('$579.00'),
    stock: 1,
    sku: 'RR0102',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:29"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '8720109954494',
    sizes: ["M"],
    brand: 'Calvin Klein',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Nautica Talla G',
    description: 'Playera Nautica Talla G.',
    imageUrl: '/images/RR0103.jpg',
    images: [{ id: 'img_RR0103_main', url: '/images/RR0103.jpg', isMain: true }],
    price: '$499.00',
    costPrice: calculateCostPrice('$499.00'),
    stock: 1,
    sku: 'RR0103',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:28"),
    barcodeType: 'UPC',
    eanGtin: '670113810485',
    sizes: ["G"],
    brand: 'Nautica',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Leggings Under Armour Talla M',
    description: 'Leggings Under Armour Talla M.',
    imageUrl: '/images/RR0095.jpg',
    images: [{ id: 'img_RR0095_main', url: '/images/RR0095.jpg', isMain: true }],
    price: '$599.00',
    costPrice: calculateCostPrice('$599.00'),
    stock: 1,
    sku: 'RR0095',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:28"),
    barcodeType: 'UPC',
    eanGtin: '194514374174',
    sizes: ["M"],
    brand: 'Under Armour',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Sudadera American Eagle Snoopy Talla CH',
    description: 'Sudadera American Eagle Snoopy Talla CH.',
    imageUrl: '/images/RR0105.jpg',
    images: [{ id: 'img_RR0105_main', url: '/images/RR0105.jpg', isMain: true }],
    price: '$1,499.00',
    costPrice: calculateCostPrice('$1,499.00'),
    stock: 1,
    sku: 'RR0105',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:27"),
    barcodeType: 'UPC',
    eanGtin: '715676587846',
    sizes: ["CH"],
    brand: 'American Eagle',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Puma Run Talla CH',
    description: 'Playera Puma Run Talla CH.',
    imageUrl: '/images/RR0098.jpg',
    images: [{ id: 'img_RR0098_main', url: '/images/RR0098.jpg', isMain: true }],
    price: '$499.00',
    costPrice: calculateCostPrice('$499.00'),
    stock: 1,
    sku: 'RR0098',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:26"),
    barcodeType: 'UPC',
    eanGtin: '197671099751',
    sizes: ["CH"],
    brand: 'Puma',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Reebok Basic Talla M',
    description: 'Playera Reebok Basic Talla M.',
    imageUrl: '/images/RR0110.jpg',
    images: [{ id: 'img_RR0110_main', url: '/images/RR0110.jpg', isMain: true }],
    price: '$349.00',
    costPrice: calculateCostPrice('$349.00'),
    stock: 1,
    sku: 'RR0110',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:20"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '7502316068963',
    sizes: ["M"],
    brand: 'Reebok',
    hasVariations: true,
  },
  {
    ...defaultNewFields,
    name: 'Playera Original Penguin Polo', // No size in name
    description: 'Playera Original Penguin Polo.',
    imageUrl: '/images/RR0109.jpg',
    images: [{ id: 'img_RR0109_main', url: '/images/RR0109.jpg', isMain: true }],
    price: '$550.00',
    costPrice: calculateCostPrice('$550.00'),
    stock: 0,
    sku: 'RR0109',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:06"),
    barcodeType: 'EAN/GTIN',
    eanGtin: '5059436551896',
    brand: 'Original Penguin', 
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Playera Original Penguin Letras', // No size
    description: 'Playera Original Penguin Letras.',
    imageUrl: '/images/RR0107.jpg',
    images: [{ id: 'img_RR0107_main', url: '/images/RR0107.jpg', isMain: true }],
    price: '$480.00',
    costPrice: calculateCostPrice('$480.00'),
    stock: 0,
    sku: 'RR0107',
    updatedAt: parseDateTimeToISO("8/5/2025", "22:53"),
    barcodeType: 'UPC',
    eanGtin: '799016281632',
    brand: 'Original Penguin',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Playera Original Penguin Estampada', // No size
    description: 'Playera Original Penguin Estampada.',
    imageUrl: '/images/RR0104.jpg',
    images: [{ id: 'img_RR0104_main', url: '/images/RR0104.jpg', isMain: true }],
    price: '$480.00',
    costPrice: calculateCostPrice('$480.00'),
    stock: 0,
    sku: 'RR0104',
    updatedAt: parseDateTimeToISO("8/5/2025", "15:56"),
    barcodeType: 'UPC',
    eanGtin: '799016281632',
    brand: 'Original Penguin',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Playera Original Penguin Bordada', // No size
    description: 'Playera Original Penguin Bordada.',
    imageUrl: '/images/RR0108.jpg',
    images: [{ id: 'img_RR0108_main', url: '/images/RR0108.jpg', isMain: true }],
    price: '$520.00',
    costPrice: calculateCostPrice('$520.00'),
    stock: 0,
    sku: 'RR0108',
    updatedAt: parseDateTimeToISO("8/5/2025", "15:53"),
    barcodeType: 'UPC',
    eanGtin: '799016281632',
    brand: 'Original Penguin',
    hasVariations: false,
  },
  {
    ...defaultNewFields,
    name: 'Playera Original Penguin Bloques', // No size
    description: 'Playera Original Penguin Bloques.',
    imageUrl: '/images/RR0106.jpg',
    images: [{ id: 'img_RR0106_main', url: '/images/RR0106.jpg', isMain: true }],
    price: '$480.00',
    costPrice: calculateCostPrice('$480.00'),
    stock: 0,
    sku: 'RR0106',
    updatedAt: parseDateTimeToISO("8/5/2025", "15:26"),
    barcodeType: 'UPC',
    eanGtin: '799016281632',
    brand: 'Original Penguin',
    hasVariations: false,
  },
  // Accesorios
  {
    ...defaultNewFields,
    name: 'Maleta Deportiva Under Armour',
    description: 'Maleta Deportiva Under Armour.',
    imageUrl: '/images/RR0093.jpg',
    images: [{ id: 'img_RR0093_main', url: '/images/RR0093.jpg', isMain: true }],
    price: '$1,099.00',
    costPrice: calculateCostPrice('$1,099.00'),
    stock: 1,
    sku: 'RR0093',
    updatedAt: parseDateTimeToISO("8/5/2025", "23:31"),
    barcodeType: 'UPC',
    eanGtin: '197778990418',
    brand: 'Under Armour',
    hasVariations: false,
  },
];


const allNewProducts: Omit<ProductItem, 'id' | 'categoryName' | 'categoryId'>[] = [
    ...parsedNewImageProducts,
    ...existingProductDefinitions
];


// Helper to create full ProductItem from the parsed data
const createFullProductItem = (
    itemData: Omit<ProductItem, 'id' | 'categoryName' | 'categoryId'>,
    categoryId: 'perfumes' | 'calzado' | 'ropa' | 'accesorios',
    categoryName: string
): ProductItem => {
    return {
        ...itemData,
        id: itemData.sku, // Use SKU as ID
        categoryId,
        categoryName,
        brand: itemData.brand || extractBrandFromName(itemData.name) || '',
    };
};

const perfumeItems: ProductItem[] = allNewProducts
    .filter(p => {
        const nameLower = p.name.toLowerCase();
        return (
            nameLower.includes('edp') || 
            nameLower.includes('edt') || 
            nameLower.includes('parfum') ||
            nameLower.includes(' ml') || 
            (nameLower.includes('set') && nameLower.includes(' ml'))
        );
    })
    .map(p => createFullProductItem(p, 'perfumes', 'Perfumes'));

const calzadoItems: ProductItem[] = allNewProducts
    .filter(p => {
        const nameLower = p.name.toLowerCase();
        return (nameLower.includes('tenis') || nameLower.includes('sandalia') || nameLower.includes('zapatilla') || nameLower.includes('zapato') || nameLower.includes('suede') || nameLower.includes('court') || nameLower.includes('runner') || nameLower.includes('charged') || nameLower.includes('boots') || nameLower.includes(' mx')  || nameLower.includes(' xm')) &&
               !perfumeItems.some(perf => perf.sku === p.sku); 
    })
    .map(p => createFullProductItem(p, 'calzado', 'Calzado'));

const ropaItems: ProductItem[] = allNewProducts
    .filter(p => {
        const nameLower = p.name.toLowerCase();
        return (nameLower.includes('playera') || nameLower.includes('camiseta') || nameLower.includes('sudadera') || nameLower.includes('leggings') || nameLower.includes('conjunto deportivo') || nameLower.includes('talla ') || nameLower.includes('tank')) &&
               !perfumeItems.some(perf => perf.sku === p.sku) &&
               !calzadoItems.some(cal => cal.sku === p.sku);
    })
    .map(p => createFullProductItem(p, 'ropa', 'Ropa'));

const accesorioItems: ProductItem[] = allNewProducts
    .filter(p => {
         const nameLower = p.name.toLowerCase();
        return (nameLower.includes('maleta') || nameLower.includes('guante') || nameLower.includes('cuerda') || nameLower.includes('mochila') || nameLower.includes('bolsa') || nameLower.includes('monedero') || nameLower.includes('lentes') || nameLower.includes('gorra') || nameLower.includes('cosmetiquera') || nameLower.includes('cartera') || nameLower.includes('reloj')) && 
               !perfumeItems.some(perf => perf.sku === p.sku) &&
               !calzadoItems.some(cal => cal.sku === p.sku) &&
               !ropaItems.some(rop => rop.sku === p.sku);
    })
    .map(p => createFullProductItem(p, 'accesorios', 'Accesorios'));


// Ensure all products are categorized. If any are left, put them in a default category or log.
const categorizedSKUs = new Set([
    ...perfumeItems.map(p => p.sku),
    ...calzadoItems.map(p => p.sku),
    ...ropaItems.map(p => p.sku),
    ...accesorioItems.map(p => p.sku),
]);

const uncategorizedProducts = allNewProducts.filter(p => !categorizedSKUs.has(p.sku));
if (uncategorizedProducts.length > 0) {
    console.warn("Uncategorized products found, adding to 'Accesorios' by default:", uncategorizedProducts.map(p => ({name: p.name, sku: p.sku })));
    uncategorizedProducts.forEach(p => {
        // Double check it's not already in accesorioItems to prevent duplicates if logic above missed it
        if (!accesorioItems.some(existingAcc => existingAcc.sku === p.sku)) {
            accesorioItems.push(createFullProductItem(p, 'accesorios', 'Accesorios'));
        }
    });
}


export const INITIAL_CATALOG_DATA: CatalogCategory[] = [
  {
    id: 'accesorios',
    name: 'Accesorios',
    description: 'Gama que te hará lucir con elegancia y estilo.',
    items: accesorioItems,
  },
  {
    id: 'calzado',
    name: 'Calzado',
    description: 'Descubre el máximo confort y performance en cada paso que das.',
    items: calzadoItems,
  },
  {
    id: 'perfumes',
    name: 'Perfumes',
    description: 'Fragancias perfectas para atraer miradas y destacar tu personalidad.',
    items: perfumeItems,
  },
  {
    id: 'ropa',
    name: 'Ropa',
    description: 'Vístete para el éxito luciendo elegancia y personalidad.',
    items: ropaItems,
  },
];


const LOCAL_STORAGE_CATALOG_KEY = 'fashionFlexLiveCatalog';

export const loadCatalogFromLocalStorage = (): CatalogCategory[] => {
  try {
    const storedCatalog = localStorage.getItem(LOCAL_STORAGE_CATALOG_KEY);
    if (storedCatalog) {
      const parsed = JSON.parse(storedCatalog);
      // Basic validation of stored data structure
      if (Array.isArray(parsed) && parsed.every(cat => cat.id && cat.name && Array.isArray(cat.items))) {
         console.log("Loaded catalog from localStorage");
        return parsed;
      } else {
        console.warn("Invalid catalog data in localStorage, using initial data from constants.ts.");
        localStorage.removeItem(LOCAL_STORAGE_CATALOG_KEY); 
      }
    }
  } catch (error) { 
    console.error("Error loading catalog from localStorage:", error);
  }
  console.log("Initializing with default catalog data from constants.ts (new extensive list).");
  return JSON.parse(JSON.stringify(INITIAL_CATALOG_DATA)); // Return a deep copy
};

export const saveCatalogToLocalStorage = (catalog: CatalogCategory[]): void => {
  try {
    localStorage.setItem(LOCAL_STORAGE_CATALOG_KEY, JSON.stringify(catalog));
  } catch (error) { 
    console.error("Error saving catalog to localStorage:", error);
  }
};
